# Generated by Django 3.2.8 on 2021-10-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='contact',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='contact',
            field=models.IntegerField(max_length=12),
        ),
    ]
