# Generated by Django 3.2.8 on 2021-10-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20211026_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Amount',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Quantity',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='contact',
            field=models.BigIntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='contact',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
